---
# tasks file for fl-kube-common
- import_tasks: ubuntu-docker.yml
  when: ansible_distribution == "Ubuntu"

- import_tasks: ubuntu-kube.yml
  when: ansible_distribution == "Ubuntu"

- import_tasks: centos-docker.yml
  when: ansible_distribution == "CentOS"

- import_tasks: centos-kube.yml
  when: ansible_distribution == "CentOS"

- name: configure net bridge for flannel
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    reload: yes
    state: present
    value: 1

- name: Configure node ip
  lineinfile:
    path: /etc/default/kubelet
    create: yes
    state: present
    line: "KUBELET_EXTRA_ARGS=--node-ip={{ansible_default_ipv4.address}}"
  notify: "roll kubelet"