---
- name: Add docker repo gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"

- name: Install docker-ce
  apt:
    name: docker-ce={{docker_version}}
    state: present
    update_cache: yes

- name: Hold docker from updating
  dpkg_selections:
    name: docker-ce
    selection: hold

- name: Start docker
  service:
    name: docker
    enabled: yes
    state: started

