---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - { role: kube-common }

- hosts: kube-master
  gather_facts: no
  roles:
    - { role: fl-kube-master, kube_user: flynshue, become: yes, become_method: sudo }
    - { role: flannel }


  
  