---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - { role: kube-common, kube_user: flynshue }

- hosts: kube-master
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - { role: fl-kube-master }


  
  