---
# tasks file for kube-join
- name: print join command
  command: kubeadm token create --print-join-command
  register: kubeadm_join
  delegate_to: "{{groups['kube-master'][0]}}"

- name: Join node to cluster
  command: "{{ kubeadm_join['stdout'] }}"
  when: inventory_hostname in groups['kube-nodes']