---
# tasks file for kube-join
- name: print join command
  delegate_to: "{{ groups[kube-master][0] }}"
  command: kubeadm token create --print-join-command
  register: kubeadm_join

- name: Join node to cluster
  command: "{{ kubeadm_join.stdout_lines[0] }}"
  when: inventory_hostname in groups[kube-nodes]